/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: (typeof import('@arco-design/web-vue'))['Button']
    ACard: (typeof import('@arco-design/web-vue'))['Card']
    ACol: (typeof import('@arco-design/web-vue'))['Col']
    ADatePicker: (typeof import('@arco-design/web-vue'))['DatePicker']
    ADivider: (typeof import('@arco-design/web-vue'))['Divider']
    AEmpty: (typeof import('@arco-design/web-vue'))['Empty']
    AInput: (typeof import('@arco-design/web-vue'))['Input']
    AInputNumber: (typeof import('@arco-design/web-vue'))['InputNumber']
    AInputSearch: (typeof import('@arco-design/web-vue'))['InputSearch']
    AList: (typeof import('@arco-design/web-vue'))['List']
    AListItem: (typeof import('@arco-design/web-vue'))['ListItem']
    AListItemMeta: (typeof import('@arco-design/web-vue'))['ListItemMeta']
    AModal: (typeof import('@arco-design/web-vue'))['Modal']
    AOption: (typeof import('@arco-design/web-vue'))['Option']
    APagination: (typeof import('@arco-design/web-vue'))['Pagination']
    APopconfirm: (typeof import('@arco-design/web-vue'))['Popconfirm']
    AProgress: (typeof import('@arco-design/web-vue'))['Progress']
    ARangePicker: (typeof import('@arco-design/web-vue'))['RangePicker']
    AResult: (typeof import('@arco-design/web-vue'))['Result']
    ASelect: (typeof import('@arco-design/web-vue'))['Select']
    ASlider: (typeof import('@arco-design/web-vue'))['Slider']
    ASpace: (typeof import('@arco-design/web-vue'))['Space']
    ASwitch: (typeof import('@arco-design/web-vue'))['Switch']
    ATabPane: (typeof import('@arco-design/web-vue'))['TabPane']
    ATabs: (typeof import('@arco-design/web-vue'))['Tabs']
    ATextarea: (typeof import('@arco-design/web-vue'))['Textarea']
    ATypography: (typeof import('@arco-design/web-vue'))['Typography']
    ATypographyParagraph: (typeof import('@arco-design/web-vue'))['TypographyParagraph']
    ATypographyTitle: (typeof import('@arco-design/web-vue'))['TypographyTitle']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
